[project]
name = "hexlet-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dj-database-url>=3.1.1",
    "django>=6.0.2",
    "pytest>=9.0.2",
    "python-dotenv>=1.2.1",
    "ruff>=0.15.1",
]
